# Creación de Arrays

### Crear un array a partir de una lista

In [6]:
import numpy as np

### Crear un array de ceros de tamaño 5x5

In [15]:
#Código crear un array de ceros de tamaño 5x5
array_zeros = np.zeros((5,5))
print(array_zeros)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Crear un array de unos de tamaño 3x3

In [16]:
#Código crear un array de unos de tamaño 3x3
array_unos = np.ones((2,3))
print(array_unos)


[[1. 1. 1.]
 [1. 1. 1.]]


### Crear un array con valores espaciados uniformemente de 0 a 9

In [19]:
#Código rear un array con valores espaciados uniformemente de 0 a 9
array_linear = np.linspace(0,9,10)
print(array_linear)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### #Crear un array con 6 valores espaciados linealmente entre 0 y 1


In [20]:
#Código crear un array con 6 valores espaciados linealmente entre 0 y 1
array_reto = np.linspace(0,1,6)
print(array_reto)


[0.  0.2 0.4 0.6 0.8 1. ]


# Operaciones Básicas

### Realizar una suma, resta, multiplicación y división entre dos arrays

In [24]:
array_salario = np.array(([50,40,20],[2,4,3]))
array_propinas = np.array(([6,4,9],[6,4,9]))

#Código realizar una suma, resta, multiplicación y división entre dos arrays

# Salida
'''
print("La suma es: ",suma)
print("La resta es: ",resta)
print("La multiplicacion es: ",multiplicacion)
print("La division es: ",division)
'''
suma = array_salario + array_propinas
resta = array_salario + array_propinas
multi = array_salario + array_propinas
divi = array_salario + array_propinas
print(suma)
print(resta)
print(multi)
print(divi)

[[56 44 29]
 [ 8  8 12]]
[[56 44 29]
 [ 8  8 12]]
[[56 44 29]
 [ 8  8 12]]
[[56 44 29]
 [ 8  8 12]]


In [ ]:
#Calcular el producto punto de dos arrays


In [ ]:
#Transponer un array


# Operaciones Estadísticas

In [27]:
#Calcular la media, suma, valor mínimo y valor máximo de un array



# Crear un array NumPy
array_numeros = np.array([5, 2, 4, 1, 3])

# Calcular la media
media = np.mean(array_numeros)
print(media)

# Calcular la suma
suma = np.sum(array_numeros)
print(suma)


# Calcular el valor mínimo
minimo = np.min(array_numeros)
print(array_numeros)


# Calcular el valor máximo
maximo = np.max(array_numeros)
print(array_numeros)

'''
# Mostrar los resultados
print("La media es:", media)
print("La suma es:", suma)
print("El valor mínimo es:", valor_minimo)
print("El valor máximo es:", valor_maximo)
'''


3.0
15
[5 2 4 1 3]
[5 2 4 1 3]


'\n# Mostrar los resultados\nprint("La media es:", media)\nprint("La suma es:", suma)\nprint("El valor mínimo es:", valor_minimo)\nprint("El valor máximo es:", valor_maximo)\n'

In [ ]:
#Cambiar la forma de un array "reshape"


# Crear un array original
array_original = np.array([1, 2, 3, 4, 5, 6])

# Nueva forma deseada (2 filas y 3 columnas)
array_reas = array_original.reshape(2,3)
print(array_original)

'''
# Imprimir el array original y el reshapeado
print("Array original:", array_original)
print("Array reshapeado:", array_reshapeado)
'''

# Álgebra Lineal

### Calcular el determinante de una matriz 2x2

In [ ]:
nuevo_array = np.array([[1,2],[2,5]])

#Código para calcular el determinante de una matriz 2x2

#print(determinante)

### Calcular la matriz inversa de una matriz 3x3

In [ ]:
# Definir la matriz 3x3


# Calcular la matriz inversa


# Imprimir la matriz inversa



### Calcular los valores propios y vectores propios de una matriz 4x4

In [ ]:

# Definir la matriz 4x4
matriz_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Calcular valores propios y vectores propios


# Separar valores propios y vectores propios
 # Parte real de los valores propios complejos
  # Parte real de los vectores propios complejos

# Imprimir resultados
'''
print("Valores propios:", autovalores)
print("Vectores propios:")
for i in range(len(autovectores)):
    print(f"Vector propio {i+1}:", autovectores[i])
'''

# Funciones Universales

In [ ]:
# Crear un array con ángulos
array_angulos = np.array([0, np.pi/2, np.pi])

# Calcular el seno de los ángulos


# Calcular el coseno de los ángulos


# Calcular la exponencial de los ángulos


# Calcular el logaritmo natural de los ángulos




In [ ]:
#Realizar indexación y slicing en un array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


# Obtener la primera fila del array


# Obtener la última columna del array
  # [3, 6, 9]

# Obtener una submatriz que contiene la segunda fila y las dos primeras columnas
  # [4, 5]

# Imprimir los subconjuntos de datos extraídos


# Generación de Números Aleatorios

In [ ]:
#Generar un array de 10 números enteros aleatorios entre 1 y 100


In [ ]:
#Generar una matriz 2x3 con números aleatorios uniformemente distribuidos entre 0 y 1


In [ ]:
#Generar un array de 5 números aleatorios con distribución normal (media 0, desviación estándar 1)



# ejercicios reales

In [28]:
# preferencias[accion ,comedia , drama]
mariana = np.array([7,9,2])

avatar = np.array([10,1,5]) # mas accion y menos comedia

Corazon_Valiente = ([8,1,7])

#Calcular similitud

similitud_p1 = np.dot(mariana,avatar)
similitud_p2 = np.dot(mariana,Corazon_Valiente)
print(f"Similitud de preferencias de mariana Avatar:{similitud_p1} ")
print(f"Similitud de preferencias de Corazon Valiente:{similitud_p2} ")

if similitud_p1 > similitud_p2:
    print("recomendados avatar")
if similitud_p2 > similitud_p1:
    print("Recomendamos Corazon Valiente")


Similitud de preferencias de mariana Avatar:89 
Similitud de preferencias de Corazon Valiente:79 
recomendados avatar


# Caso Real 

In [33]:
import numpy as np
#Datos Tipo Cambio Dolar Ultimos 10 meses | IPC , metrica mesual


tipo_cambio = np.array([506.96,505.00,504.27,505.52,506.23,506.23,506.23,506.58,506.87,507.25])
ipc = np.array([109.46,109.55,109.71,109.57,109.70,109.33,108.85, 109.36,110.39,110.79])


#Calcular coeficiente de correlación
correlacion =  np.corrcoef(tipo_cambio,ipc)[0,1]


print(f'Coeficiente de correlación: {correlacion:.2f}')

Coeficiente de correlación: 0.32


In [37]:
import numpy as np

horas_estudio = np.array([1,2,3,4,5,6,7,8,9,10])
notas = np.array([50,55,60,63,67,72,75,78,81,85])
diferencia_notas = np.diff(notas)
incremento = np.average(diferencia_notas)

estudio = 12
nota_estimada = (estudio - horas_estudio[-1]) * incremento
print(f"El incrementos de notas pore cada hora de estudio es de :{incremento:.2f}")
print(nota_estimada)

El incrementos de notas pore cada hora de estudio es de :3.89
7.777777777777778
